version: "3.5"

networks:
    default:
        name: ${VDK_NETWORK_NAME}
        external: true

services:
    mysql:
        image: ${VDK_PREFIX}mysql
        container_name: ${VDK_PREFIX}mysql
        command: mysqld --user=root
        build:
            context: ${VDK_PATH}/docker/images/mysql
            args:
                - version=latest
        env_file:
            - ./../.env
        ports:
            - ${VDK_MYSQL_PORT}:3306