version: "3.5"

networks:
    default:
        name: ${VDK_NETWORK_NAME}
        external: true

services:
    nginx:
        image: ${VDK_PREFIX}nginx
        container_name: ${VDK_PREFIX}nginx
        build:
            context: ${VDK_PATH}/docker/images/nginx
            args:
                - version=latest
                - nginx_conf_path=${VDK_PATH}/projects/${VDK_PROJECT_NAME}/nginx.conf
        ports:
            - ${VDK_NGINX_PORT}:80
        env_file:
            - ./../.env
        volumes:
            - ${VDK_WWW_PATH}:${VDK_DOCKER_WWW_PATH}
            - ./../nginx/hosts:/etc/nginx/conf.d
            - ./../nginx/logs:/var/log/nginx