version: "3.5"

networks:
    nginx_net:
        name: ${VDK_NGINX_NETWORK_NAME}
        external: ${VDK_NGINX_NETWORK_EXTERNAL}
    php56_net:
        name: ${VDK_PHP56_NETWORK_NAME}
        external: ${VDK_PHP56_NETWORK_EXTERNAL}
    php70_net:
        name: ${VDK_PHP70_NETWORK_NAME}
        external: ${VDK_PHP70_NETWORK_EXTERNAL}
    php71_net:
        name: ${VDK_PHP71_NETWORK_NAME}
        external: ${VDK_PHP71_NETWORK_EXTERNAL}
    mariadb_net:
        external: ${VDK_MARIADB_NETWORK_EXTERNAL}
        name: ${VDK_MARIADB_NETWORK_NAME}
    pma_net:
        external: ${VDK_PMA_NETWORK_EXTERNAL}
        name: ${VDK_PMA_NETWORK_NAME}

services:
    nginx:
        image: ${VDK_NGINX_IMAGE_NAME}
        build: ${VDK_NGINX_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_nginx
        ports:
            - ${VDK_NGINX_PORT}:80
        networks:
            - nginx_net
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}
    php56:
        image: ${VDK_PHP56_IMAGE_NAME}
        build: ${VDK_PHP56_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_${VDK_PHP56_IMAGE_NAME}
        user: www-data
        networks:
            - php56_net
        volumes:
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}
    php70:
        image: ${VDK_PHP70_IMAGE_NAME}
        build: ${VDK_PHP70_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_${VDK_PHP70_IMAGE_NAME}
        user: www-data
        networks:
            - php70_net
        volumes:
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}
    php71:
        image: ${VDK_PHP71_IMAGE_NAME}
        build: ${VDK_PHP71_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_${VDK_PHP71_IMAGE_NAME}
        user: www-data
        networks:
            - php71_net
        volumes:
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}
    mariadb:
        image: ${VDK_MARIADB_IMAGE_NAME}
        build: ${VDK_MARIADB_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_mariadb
        env_file:
            - ./.env
        networks:
            - mariadb_net
        ports:
            - ${VDK_MARIADB_PORT}:3306
        volumes:
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}
            - ./data/mariadb:/var/local
    pma:
        image: ${VDK_PMA_IMAGE_NAME}
        build: ${VDK_PMA_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_pma
        restart: always
        env_file:
            - ./.env
        networks:
            - pma_net
        ports:
            - ${VDK_PMA_PORT}:80