version: "3.5"

networks:
    default:
        name: ${VDK_NGINX_NETWORK_NAME}
        external: ${VDK_NGINX_NETWORK_EXTERNAL}

services:
    nginx:
        image: ${VDK_NGINX_IMAGE_NAME}
        build: ${VDK_NGINX_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_${VDK_NGINX_IMAGE_NAME}
        ports:
            - ${VDK_NGINX_PORT}:80
        networks:
            - default
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}