version: "3.5"

networks:
    default:
        name: ${VDK_NETWORK_NAME}
        external: true

services:
    mariadb:
        image: ${VDK_PREFIX}mariadb
        container_name: ${VDK_PREFIX}mariadb
        #command: faketime -m -f ${VDK_DOCKER_FAKETIME} mysqld --user=mysql
        command: mysqld --user=mysql
        build:
            context: ./../../../docker/images/mariadb
            args:
                - version=latest
        env_file:
            - ./../.env
        ports:
            - ${VDK_MYSQL_PORT}:3306