version: "3.5"

networks:
    default:
        name: ${VDK_NETWORK_NAME}
        external: true

services:
    nginx:
        image: ${VDK_PREFIX}nginx
        container_name: ${VDK_PREFIX}nginx
        build:
            context: ./../../../docker/images/nginx
            args:
                - version=latest
                - nginx_conf_path=${VDK_HOST_PATH}/projects/${VDK_PROJECT_NAME}/nginx.conf
        ports:
            - 80:80
        env_file:
            - ./../.env
        volumes:
            - ${VDK_HOST_WWW_PATH}:${VDK_DOCKER_WWW_PATH}
            - ./../nginx/hosts:/etc/nginx/conf.d
            - ./../nginx/logs:/var/log/nginx