version: "3.5"

networks:
    default:
        name: ${VDK_NETWORK_NAME}
        external: true

services:
    mysql:
        image: ${VDK_MYSQL_IMAGE_NAME}
        build:
            context: ${VDK_MYSQL_IMAGE_PATH}
            args:
                - version=${VDK_MYSQL_IMAGE_VERSION}

        container_name: ${VDK_DOCKER_ID}_${VDK_MYSQL_IMAGE_NAME}
        command: faketime -f ${VDK_DOCKER_FAKETIME} mysqld --user=root
        env_file:
            - ${VDK_DOCKER_HOST_PATH}/.env
        networks:
            - default
        ports:
            - ${VDK_MYSQL_PORT}:3306
        volumes:
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}
            - ${VDK_DOCKER_HOST_PATH}/data/mysql:/var/local