version: "3.5"

services:
    nginx:
        image: ${VDK_NGINX_IMAGE_NAME}
        build:
            context: ${VDK_NGINX_IMAGE_PATH}
            args:
                - version=${VDK_NGINX_IMAGE_VERSION}
        container_name: ${VDK_DOCKER_ID}_${VDK_NGINX_IMAGE_NAME}
        ports:
            - ${VDK_NGINX_PORT}:80
        network_mode: host
        #networks:
        #    - default
        env_file:
            - ${VDK_DOCKER_HOST_PATH}/.env
        volumes:
            - ${VDK_DOCKER_HOST_PATH}:${VDK_DOCKER_GUEST_PATH}
            - ${VDK_DOCKER_HOST_WWW_PATH}:${VDK_DOCKER_GUEST_WWW_PATH}
            - ${VDK_DOCKER_HOST_PATH}/hosts:/etc/nginx/conf.d
            - ${VDK_DOCKER_HOST_PATH}/logs/nginx:/var/log/nginx