version: "3.5"

networks:
    default:
        name: ${VDK_NETWORK_NAME}
        external: true

services:
    pma:
        image: ${VDK_PMA_IMAGE_NAME}
        build: ${VDK_PMA_IMAGE_PATH}
        container_name: ${VDK_DOCKER_ID}_${VDK_PMA_IMAGE_NAME}
        restart: always
        networks:
            - default
        ports:
            - ${VDK_PMA_PORT}:80
        env_file:
            - ${VDK_DOCKER_HOST_PATH}/.env